[python] 
format = "[$symbol$version]($style) [$virtualenv](bold green)" 

[git_branch] 
symbol = "🌱 "
format = "[$symbol$branch]($style) " 

[git_commit]
commit_hash_length = 7
only_detached = false
tag_symbol = "🏷"

[git_status]
conflicted = "🏳"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "✓"
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[git_state]
format = "[\\($state\\)]($style) "

[git_metrics]
disabled = false
format = "([+$added]($added_style) [-$deleted]($deleted_style) )"

[directory] 
style = "bold cyan" 
truncation_length = 0 
truncate_to_repo = false 
format = "[$path]($style)[$read_only]($read_only_style) "
