format = """
$directory\
$git_branch\
$python\
$character
"""

[python]
symbol = "Python: "
format = "[$symbol$version]($style) "

[git_branch]
symbol = "Git: "
format = "[$symbol$branch]($style) "

[directory]
style = "cyan"
truncation_length = 3

[character]
success_symbol = "\n[➜](bold green) "
error_symbol = "[✗](bold red) "
